# Generated by Django 5.0.3 on 2024-03-15 05:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0002_course_alter_person_options_person_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='cource_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('an', 'Android')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='person',
            name='cource',
            field=models.ManyToManyField(blank=True, to='scool.course'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'cource_num')},
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.person')),
            ],
        ),
    ]
