# Generated by Django 5.0.3 on 2024-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0004_alter_grade_options_rename_cource_person_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cource_num',
            field=models.SmallIntegerField(default=0, verbose_name='Номер курса'),
        ),
    ]
