# Generated by Django 5.0.3 on 2024-03-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0005_course_cource_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cource_num',
        ),
    ]
