# Generated by Django 5.0.3 on 2024-03-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0006_remove_course_cource_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scool.person', verbose_name='Чья оценка'),
        ),
    ]
