# Generated by Django 5.0.3 on 2024-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0007_alter_grade_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='ФОто'),
        ),
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ManyToManyField(blank=True, to='scool.course', verbose_name='Посещаемые курсы'),
        ),
    ]
