# Generated by Django 5.0.3 on 2024-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0008_person_photo_alter_person_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
